[build]
  base = "packages/client"
  command = "pnpm install && pnpm build"
  publish = "packages/client/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
