/* Autogenerated file. Do not edit manually. */

import { TableId } from '@latticexyz/utils';
import { defineComponent, Type as RecsType, World } from '@latticexyz/recs';

export function defineContractComponents(world: World) {
  return {
    Position: (() => {
      const tableId = new TableId('', 'Position');
      return defineComponent(
        world,
        {
          x: RecsType.BigInt,
          y: RecsType.BigInt
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString()
          }
        }
      );
    })(),
    Space: (() => {
      const tableId = new TableId('', 'Space');
      return defineComponent(
        world,
        {
          value: RecsType.Number
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString()
          }
        }
      );
    })(),
    Planet: (() => {
      const tableId = new TableId('', 'Planet');
      return defineComponent(
        world,
        {
          biome: RecsType.Number,
          size: RecsType.Number
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString()
          }
        }
      );
    })()
  };
}
