// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum BiomeType {
  VOID,
  OCEAN,
  FOREST,
  DESERT
}

enum PlanetSize {
  VOID,
  DWARF,
  GIANT,
  SUPER_GIANT
}

enum SpaceType {
  VOID,
  NEBULA,
  SPACE,
  DEEP_SPACE
}
