// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function getSpaceType(int256 x, int256 y) external pure returns (uint256);
}
